#!/bin/bash

export DYLD_FALLBACK_LIBRARY_PATH=${DYLD_FALLBACK_LIBRARY_PATH}:/Users/makarp/repos/json_install/lib

for gamma in 0 0.000001 0.00001 0.0001 0.001 0.002 0.005 0.006 0.007 0.008 0.009 0.01 0.02 0.03 0.04 0.05 0.1 0.2 0.5 1.0
do
    sed -e "s/0.05/$gamma/g" template.case > run.case
    echo 'running gamma =' $gamma
    mkdir gamma_$gamma
    mpirun -n 8 ./neko run.case > log_$gamma
    echo 'done gamma =' $gamma
done
